add markup and styles
nataliematiuhenko/responsive-web-page pull request #1
Opened 2019-11-06 16:03 UTC by nataliematiuhenko

This is a responsive web page.

2019-11-06 16:11 UTC, karmeljuk requested changes
minor changes: id to class

2019-11-06 16:11 UTC, karmeljuk commented on style.css
> +#section5,
it's better don't use id in css at all

2019-11-06 16:11 UTC, karmeljuk commented on style.css
> +  #logo-section {
change id to class

2019-11-07 13:49 UTC, nataliematiuhenko commented
Sorry for messing up with pull requests and commits.
Have hanged selectors in both files.

2019-11-07 17:31 UTC, merged

2019-11-07 17:31 UTC, karmeljuk reviewed
code ok